import { Header } from '@/components/header';
import '../styles/globals.css';
import { cn } from '@/lib/utils';
import { Profile } from '@/components/profile';
import localFont from 'next/font/local';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const canela = localFont({
  variable: '--font-canela',
  src: [
    {
      path: './fonts/canela_light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/canela_medium.otf',
      weight: '500',
      style: 'normal',
    },
  ],
  display: 'swap',
});

const tt_commons = localFont({
  variable: '--font-tt-commons',
  src: [
    {
      path: './fonts/tt_commons_bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/tt_commons_regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={cn(`${tt_commons.variable} ${canela.variable}`)}>
      <body
        className={cn(
          'text-lg max-w-screen-xl mx-auto text-primary overflow-x-hidden relative'
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
